name: Build Windows Executable
permissions: write-all
on:
  push:
    branches:
      - master
    paths:
      - "src/**"
      - ".github/workflows/build_executable.yml"
jobs:
  build-windows:
    name: Build for Windows
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Install PyInstaller
        run: pip install pyinstaller
      - name: Run PyInstaller for Pillow_PNG_TGA_Editor, Mirror_Concat_IMG and Split_Eyes_IMG
        run: |
          set PYTHONOPTIMIZE=2
          pyinstaller --onefile --name="Pillow_PNG_TGA_Editor" --console --icon=src\Pillow_PNG_TGA_Editor\images\Pillows_Hat_Icon.tga --add-data="src\Pillow_PNG_TGA_Editor\images:images" --add-data="src\Pillow_PNG_TGA_Editor\localization:localization" src\Pillow_PNG_TGA_Editor\pillow_png_tga_editor.py
          pyinstaller --onefile --name="Mirror_Concat_IMG" --console --icon=src\Pillow_PNG_TGA_Editor\images\Pillows_Hat_Icon_Mirror.tga --add-data="src\Pillow_PNG_TGA_Editor\images:images" --add-data="src\Pillow_PNG_TGA_Editor\localization:localization" src\Pillow_PNG_TGA_Editor\mirror_concat_img.py
          pyinstaller --onefile --name="Split_Eyes_IMG" --console --icon=src\Pillow_PNG_TGA_Editor\images\Pillows_Hat_Icon_Split.tga --add-data="src\Pillow_PNG_TGA_Editor\images:images" --add-data="src\Pillow_PNG_TGA_Editor\localization:localization" src\Pillow_PNG_TGA_Editor\split_eyes_img.py
      - name: Move Executables from dist to root directory
        run: |
          move dist\Pillow_PNG_TGA_Editor.exe .
          move dist\Mirror_Concat_IMG.exe .
          move dist\Split_Eyes_IMG.exe .
          rd /s /q dist
        shell: cmd
      - name: Create Automatic Windows Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: latest
          prerelease: false
          title: Latest Build
          files: |
            Pillow_PNG_TGA_Editor.exe
            Mirror_Concat_IMG.exe
            Split_Eyes_IMG.exe