name: Build Windows Executable
on:
  push:
    branches:
      - master
jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install requirements
        run: pip install pillow tqdm i18nice[YAML] pyinstaller
      - name: Run PyInstaller
        run: pyinstaller --onefile --name="Pillow_PNG_TGA_Editor" --add-data=images:images --add-data=localization:localization --console --icon=images\Pillows_Hat_Icon.tga main.py
      - name: Create Automatic Windows Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: latest
          prerelease: false
          title: Latest Build
          files: dist/*