name: Build Windows Executable with Nuitka
permissions: write-all
on:
  push:
    branches:
      - master
    paths:
      - "src/**"
      - ".github/workflows/build_executable_nuitka.yml"
jobs:
  build-windows:
    name: Build for Windows
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Install requirements
        run: |
          pip install -r requirements.txt
          pip install imageio
      - name: Run Nuitka for Pillow_PNG_TGA_Editor
        uses: Nuitka/Nuitka-Action@main
        with:
          nuitka-version: main
          script-name: src/Pillow_PNG_TGA_Editor/pillow_png_tga_editor.py
          mode: app
          enable-plugins: tk-inter
          include-data-dir: |
            src/Pillow_PNG_TGA_Editor/localization=localization
            src/Pillow_PNG_TGA_Editor/images=images
          windows-icon-from-ico: src/Pillow_PNG_TGA_Editor/images/Pillows_Hat_Icon.tga
      - name: Run Nuitka for Mirror_Concat_IMG
        uses: Nuitka/Nuitka-Action@main
        with:
          nuitka-version: main
          script-name: src/Pillow_PNG_TGA_Editor/mirror_concat_img.py
          mode: app
          enable-plugins: tk-inter
          include-data-dir: |
            src/Pillow_PNG_TGA_Editor/localization=localization
            src/Pillow_PNG_TGA_Editor/images=images
          windows-icon-from-ico: src/Pillow_PNG_TGA_Editor/images/Pillows_Hat_Icon_Mirror.tga
      - name: Run Nuitka for Split_Eyes_IMG
        uses: Nuitka/Nuitka-Action@main
        with:
          nuitka-version: main
          script-name: src/Pillow_PNG_TGA_Editor/split_eyes_img.py
          mode: app
          enable-plugins: tk-inter
          include-data-dir: |
            src/Pillow_PNG_TGA_Editor/localization=localization
            src/Pillow_PNG_TGA_Editor/images=images
          windows-icon-from-ico: src/Pillow_PNG_TGA_Editor/images/Pillows_Hat_Icon_Split.tga
      - name: Move Executables from build to root directory
        run: |
          move build\Pillow_PNG_TGA_Editor.exe .
          move build\Mirror_Concat_IMG.exe .
          move build\Split_Eyes_IMG.exe .
          rd /s /q build
        shell: cmd
      - name: Create Automatic Windows Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: latest-nuitka
          prerelease: false
          title: Latest Nuitka Build
          files: |
            Pillow_PNG_TGA_Editor.exe
            Mirror_Concat_IMG.exe
            Split_Eyes_IMG.exe